;;;; fmt-better.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import chicken scheme fmt listicles srfi-13 data-structures))
(##sys#register-compiled-module
  'fmt-better
  (list)
  '((fmt-rows . fmt-better#fmt-rows))
  (list)
  (list))

;; END OF FILE
