;;;; fmt-better.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'fmt-better
      'fmt-better
      (scheme#list)
      '((fmt-rows . fmt-better#fmt-rows))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
