;;;; hey-dates.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import chicken scheme srfi-19 posix ports))
(##sys#register-compiled-module
  'hey-dates
  (list)
  '((date-at-midnight . hey-dates#date-at-midnight)
    (date-at-midnight-x-days-ago . hey-dates#date-at-midnight-x-days-ago)
    (seconds-at-midnight . hey-dates#seconds-at-midnight)
    (seconds-at-midnight-minus-days . hey-dates#seconds-at-midnight-minus-days)
    (subtract-days-from-epoch . hey-dates#subtract-days-from-epoch)
    (date->sqlite-string . hey-dates#date->sqlite-string))
  (list)
  (list))

;; END OF FILE
