;;;; hey-dates.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'hey-dates
      'hey-dates
      (scheme#list)
      '((date-at-midnight . hey-dates#date-at-midnight)
        (date-at-midnight-x-days-ago . hey-dates#date-at-midnight-x-days-ago)
        (seconds-at-midnight . hey-dates#seconds-at-midnight)
        (seconds-at-midnight-minus-days
          .
          hey-dates#seconds-at-midnight-minus-days)
        (subtract-days-from-epoch . hey-dates#subtract-days-from-epoch)
        (date->sqlite-string . hey-dates#date->sqlite-string))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
