;;;; interrupt-database.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'interrupt-database
      'interrupt-database
      (scheme#list)
      '((load-db-at-path . interrupt-database#load-db-at-path)
        (create-tag . interrupt-database#create-tag)
        (find-id-of-person . interrupt-database#find-id-of-person)
        (create-person . interrupt-database#create-person)
        (create-people . interrupt-database#create-people)
        (find-or-create-person . interrupt-database#find-or-create-person)
        (find-or-create-people . interrupt-database#find-or-create-people)
        (join-person-to-event . interrupt-database#join-person-to-event)
        (event-ids-with-person . interrupt-database#event-ids-with-person)
        (delete-person-from-db . interrupt-database#delete-person-from-db)
        (find-id-of-tag . interrupt-database#find-id-of-tag)
        (create-event . interrupt-database#create-event)
        (find-event-by-id . interrupt-database#find-event-by-id)
        (get-last-event-id . interrupt-database#get-last-event-id)
        (join-tag-to-event . interrupt-database#join-tag-to-event)
        (join-tags-to-event . interrupt-database#join-tags-to-event)
        (event-has-tag? . interrupt-database#event-has-tag?)
        (delete-events-from-db . interrupt-database#delete-events-from-db)
        (delete-events-with-person
          .
          interrupt-database#delete-events-with-person)
        (find-tags . interrupt-database#find-tags)
        (comment-on-event . interrupt-database#comment-on-event))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
