;;;; interrupts-by-day-report.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         srfi-1
         srfi-69
         sql-de-lite
         extras
         loops
         listicles
         uri-tools
         data-structures))
(##sys#register-compiled-module
  'interrupts-by-day-report
  (list)
  '((graph-interrupts-by-day
      .
      interrupts-by-day-report#graph-interrupts-by-day))
  (list)
  (list))

;; END OF FILE
