;;;; interrupts-by-day-report.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'interrupts-by-day-report
      'interrupts-by-day-report
      (scheme#list)
      '((graph-interrupts-by-day
          .
          interrupts-by-day-report#graph-interrupts-by-day))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
