;;;; listicles.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import chicken scheme srfi-1 srfi-69 extras data-structures loops))
(##sys#register-compiled-module
  'listicles
  (list)
  '((nth . listicles#nth)
    (range . listicles#range)
    (split-by . listicles#split-by)
    (list-includes . listicles#list-includes)
    (pairs-list-to-hash . listicles#pairs-list-to-hash)
    (replace-nth . listicles#replace-nth)
    (last-index . listicles#last-index)
    (sort-strings> . listicles#sort-strings>)
    (sort-strings< . listicles#sort-strings<)
    (convert-rows-to-cols . listicles#convert-rows-to-cols))
  (list)
  (list))

;; END OF FILE
