;;;; listicles.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'listicles
      'listicles
      (scheme#list)
      '((acons . listicles#acons)
        (assoc-set . listicles#assoc-set)
        (alist-merge . listicles#alist-merge)
        (all? . listicles#all?)
        (any? . listicles#any?)
        (convert-rows-to-cols . listicles#convert-rows-to-cols)
        (first-where . listicles#first-where)
        (insert-last . listicles#insert-last)
        (last-index . listicles#last-index)
        (list-by-index . listicles#list-by-index)
        (list-includes? . listicles#list-includes?)
        (mflatten . listicles#mflatten)
        (nth . listicles#nth)
        (nth1 . listicles#nth1)
        (pairs-list-to-hash . listicles#pairs-list-to-hash)
        (range . listicles#range)
        (replace-nth . listicles#replace-nth)
        (sort-strings< . listicles#sort-strings<)
        (sort-strings> . listicles#sort-strings>)
        (split-by . listicles#split-by))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
