;;;; listicles.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import chicken scheme srfi-1))
(##sys#register-compiled-module
  'listicles
  (list)
  '((nth . listicles#nth)
    (range . listicles#range)
    (split-by . listicles#split-by)
    (list-includes . listicles#list-includes))
  (list)
  (list))

;; END OF FILE
