;;;; people-by-hour.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         sql-de-lite
         loops
         srfi-69
         listicles
         uri-tools
         srfi-1))
(##sys#register-compiled-module
  'people-by-hour
  (list)
  '((graph-people-by-hour . people-by-hour#graph-people-by-hour))
  (list)
  (list))

;; END OF FILE
