;;;; uri-tools.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         posix
         ports
         extras
         http-client
         data-structures
         listicles
         uri-common
         json))
(##sys#register-compiled-module
  'uri-tools
  (list)
  '((generate-graph-url . uri-tools#generate-graph-url)
    (json->uri-string . uri-tools#json->uri-string)
    (json->string . uri-tools#json->string)
    (open-url . uri-tools#open-url)
    (post-graph-data . uri-tools#post-graph-data))
  (list)
  (list))

;; END OF FILE
