;;;; uri-tools.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'uri-tools
      'uri-tools
      (scheme#list)
      '((generate-graph-url . uri-tools#generate-graph-url)
        (json->uri-string . uri-tools#json->uri-string)
        (json->string . medea#json->string)
        (open-url . uri-tools#open-url)
        (post-graph-data . uri-tools#post-graph-data))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
