;;;; who-list.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'who-list
      'who-list
      (scheme#list)
      '((graph-who . who-list#graph-who))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
