;;;; who-list.import.scm - GENERATED BY CHICKEN 4.11.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         srfi-1
         srfi-13
         srfi-69
         listicles
         fmt-better
         loops
         sql-de-lite
         data-structures))
(##sys#register-compiled-module
  'who-list
  (list)
  '((graph-who . who-list#graph-who))
  (list)
  (list))

;; END OF FILE
