;;;; x-by-hour-report.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'x-by-hour-report
      'x-by-hour-report
      (scheme#list)
      '((graph-x-by-hour . x-by-hour-report#graph-x-by-hour))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
